version: "3.8"

services:
  app:
    build: .
    environment:
      - QUARKUS_PROFILE=dev
    ports:
      - "8085:8085"
    depends_on:
      - redis
      - localstack
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    networks:
      - app-network

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge